<?php

class ZBookTableSeeder extends Seeder
{


	public function run()
	{
		DB::table('books')->delete();
		$book = new Book;
		$book->title = 'คู่มือปลูกมะนาว ฉบับสมบูรณ์';
		$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/527/9786165277914L.jpg';
		$book->save();
		$author = new Author;
		//$author->prefix = '';
		// $author->first_name = 'เอนก';
		// $author->last_name = 'นาวิกมูล';
		$author->pseudonym = 'บรรพดี';
		$author->save();
		$book->author()->attach($author->id);
		//ถ้ามีหลายคนก็ new author อีก
		//ถ้ามี translator
		// $translator = new Translator;
		// $translator->prefix = '';
		// $translator->first_name = 'เอนก';
		// $translator->last_name = 'นาวิกมูล';
		// $translator->pseudonym = '';
		// $translator->save();
		// $book->translator()->attach($translator->id);
		//ถ้ามีหลายคนก็ new translator อีก
		$book->cover_price         = 125;
		$book->sell_price = 118.75;
		$tag = new Tag;
		$tag->name = 'การปลูกมะนาว';
		$tag->save();
		$book->tag()->attach($tag->id);
		$tag = new Tag;
		$tag->name = 'พืชและการเกษตร';
		$tag->save();
		$book->tag()->attach($tag->id);
		$tag = new Tag;
		$tag->name = 'พืชเศรษฐกิจ';
		$tag->save();
		$book->tag()->attach($tag->id);
		$tag = new Tag;
		$tag->name = 'มะนาว';
		$tag->save();
		$book->tag()->attach($tag->id);
		$book->ISBN = '9786165089555';
		$book->barcode = '9786165089555';
		$book->width = 185;
		$book->high = 210;
		$book->deep = 7;
		$book->weight = 270;
		$book->type = 'สี่สีในเล่ม';
		$book->publisher_name= 'เอ็มไอเอส, สนพ.';
		// $test = new DateTime('01/2015');
		// $book->pub_date = $test;
		$category = new Category;
		$category->name = 'พืชและการเกษตร';
		$category->save();
		$book->category_id = $category->id;
		// $category_id = Category::where('name','=','พืชและการเกษตร')->get()->first()->id;
		// $book->category_id = $category_id;
		$sub_category = new SubCategory;
		$sub_category->name = 'ผักทั่วไป';
		$sub_category->save();
		$book->sub_category_id = $sub_category->id;
		// $sub_category_id = SubCategory::where('name','=','ผักทั่วไป')->get()->first()->id;
		// $book->sub_category_id = $sub_category_id;
		$book->description = '"มะนาว" เป็นพืชที่อยู่คู่คนไทยมานานและมีมูลค่าทางเศรษฐกิจสูงชนิดหนึ่ง ทั้งยังเป็นที่สนใจของเกษตรกรรุ่นใหม่ซึ่งกำลังมองหาพืชสักชนิดมาปลูกเพื่อสร้างรายได้ ปัจจุบันมะนาวได้รับการพัฒนาสายพันธุ์เพื่อให้ผลผลิตดีและต้านทางโรค รวมถึงพัฒนาวิธีการปลูกต่างๆ ให้ประสบความสำเร็จ     หนังสือเล่มนี้ได้รวบรวมวิธีปลูกมะนาวหลายรูปแบบ เทคนิคต่างๆ อาทิ ปลูกในพื้นดิน ปลูกในวงบ่อซีเม็นต์ ปลูกไร้ดิน หรือปลูกในกระถาง ซึ่งเหมาะสำหรับผู้ที่มีพื้นที่จำกัด ตลอดจนแนะนำวิธีปลูกมะนาวนอกฤดูกาล พร้อมสูตรปุ๋ยชีวภาพสำหรับบำรุงรักษาและช่วยเพิ่มผลผลิตให้มะนาวเพื่อเพิ่มมูลค่า ถ่ายทอดประสบการณ์ความรู้โดยเจ้าของสวนตัวจริง ครบทุกรายละเอียดและขั้นตอนแบบมืออาชีพที่มือใหม่ก็ทำได้';
		
		$book->save();
		$book = new Book;
		$book->title = 'คิดต้องทำ คันต้องเกา – Stop Talking, Start Doing';
		$book->cover_pic          = 'http://www.rvbookthai.com/wp-content/uploads/2013/06/-e1403758443341.jpg';
		$book->save();
		$author = new Author;
		$author->prefix = '';
		$author->first_name = 'Wasmund';
		$author->last_name = 'Shaa';
		$author->pseudonym = '';
		$author->save();
		$book->author()->attach($author->id);
		$author = new Author;
		$author->prefix = '';
		$author->first_name = 'Newton';
		$author->last_name = 'Richard';
		$author->pseudonym = '';
		$author->save();
		$book->author()->attach($author->id);
		//ถ้ามีหลายคนก็ new author อีก
		//ถ้ามี translator
		$translator = new Translator;
		$translator->prefix = '';
		$translator->first_name = 'ปฏิพล';
		$translator->last_name = 'ตั้งจักรวรานนท์';
		$translator->pseudonym = '';
		$translator->save();
		$book->translator()->attach($translator->id);
		//ถ้ามีหลายคนก็ new translator อีก
		$book->cover_price         = 170.00;
		$book->sell_price = 161.50;
		$tag = new Tag;
		$tag->name = 'Stop Talking';
		$tag->save();
		$book->tag()->attach($tag->id);
		$tag = new Tag;
		$tag->name = 'Start Doing';
		$tag->save();
		$book->tag()->attach($tag->id);
		$tag = new Tag;
		$tag->name = 'แรงบัลดาลใจ';
		$tag->save();
		$book->tag()->attach($tag->id);
		$book->ISBN = '9786162870200';
		$book->barcode = '9786162870200';
		$book->page = 120;
		$book->width = 138;
		$book->high = 210;
		$book->deep = 12;
		$book->weight = 310;
		$book->type = 'ขาว-ดำ/สี';
		$book->publisher_name= 'วีเลิร์น, สนพ.';
		// $test = new DateTime('01/2015');
		// $book->pub_date = $test;
		$category = new Category;
		$category->name = 'จิตวิทยาทั่วไป';
		$category->save();
		$book->category_id = $category->id;
		// $category_id = Category::where('name','=','จิตวิทยาทั่วไป')->get()->first()->id;
		// $book->category_id = $category_id;
		$sub_category = new SubCategory;
		$sub_category->name = 'การพัฒนาตนเอง';
		$sub_category->save();
		$book->sub_category_id = $sub_category->id;
		// $sub_category_id = SubCategory::where('name','=','การพัฒนาตนเอง')->get()->first()->id;
		// $book->sub_category_id = $sub_category_id;
		$book->description = 'คุณอาจอยากเรียนต่อ เปลี่ยนงาน ลดรอบเอว ปีนเขาหิมาลัย เขียนหนังสือ หรือสร้างธุรกิจของตัวเอง ตอนแรกคุณมุ่งมั่นว่าจะทำตามเป้าหมายให้สำเร็จ แต่เมื่อเวลาผ่านไป ไฟในตัวคุณก็ดับมอดไปเฉยๆ แทนที่อาการคันไม้คันมืออยากจะทำสิ่งต่างๆ จะทุเลาลง มันกลับทวีความรุนแรง จากที่เคยคันยิกๆ กลายเป็นคันคะเยอ คำถามคือ จะปล่อยให้มันสร้างความระคายเคืองให้ชีวิตไปอีกนานแค่ไหน!?!       หนังสือเล่มนี้จะสอนวิธีเกาให้ถูกที่คัน ไม่ว่าอาการคันจะเกิดจากอะไร คุณจะมองเห็นตำแหน่งของมันได้ชัดเจนยิ่งขึ้น คุณจะเกิดความฮึกเหิม ลุกขึ้นมากำจัดอุปสรรคทุกอย่าง เอาชนะเสียงต่อต้านจากคนรอบข้าง หรือแม้แต่เสียงคัดค้านในหัวของคุณเอง แล้วลงมือทำในที่สุด ความจริงก็คือ สิ่งเดียวที่คุณควรผัดผ่อนไปทำพรุ่งนี้คือสิ่งที่แม้จะไม่ได้ทำ คุณก็ยังตายตาหลับ ฉะนั้น อย่าปล่อยให้อาการคันสร้างความรำคาญได้อีก ลงมือเกาซะที เริ่มตอนนี้เลย!';
		
		$book->save();
		$book = new Book;
$book = new Book;
$book->title = 'พยัคฆราชซ่อนเล็บ ภาค 2 เล่ม 2';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/369/9786163694065L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'Yue';
$author->last_name = 'Guan';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$translator = new Translator;
$translator->prefix = '';
$translator->first_name = '';
$translator->last_name = '';
$translator->pseudonym = 'น.นพรัตน์';
$translator->save();
$book->translator()->attach($translator->id);
$book->cover_price         = 210.00;
$book->sell_price = 199.50;
$book->ISBN = '9786163694065';
$book->barcode = '9786163694065';
$book->type = 'ปกอ่อน';
$book->page = 264;
$book->width = 142;
$book->high = 204;
$book->deep = 15;
$book->weight = 310;
$book->publisher_name= 'สยามอินเตอร์บุ๊คส์, สนพ.';
$category = new Category;
$category->name = 'กำลังภายใน';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'นวนิยาย';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เซี่ยสิน ได้รับพระบัญชาจากหย่งเล่อฮ่องเต้ ให้เดินทางไปยังแดนเหลียวตง เพื่อจัดการกับปัญหาชายแดนแต่ในดินแดนที่เต็มไปด้วยชนเผ่าอันมากมาย เซี่ยสินจะสามารถทำตามพระบัญชา หย่งเล่อฮ่องเต้สำเร็จหรือไม่';
$book->save();
$tag = new Tag;
$tag->name = 'พยัคฆราชซ่อนเล็บ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'นวนิยายจีนกำลังภายใน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'นวนิยายจีน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'นวนิยายกำลังภายใน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'นวนิยายอิงประวัติศาสตร์';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'เปลี่ยนวิธีทำงานแค่ 1% คุณก็จะแซงหน้าคน 99% ได้แล้ว';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/287/9786162870842L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'Eitaro';
$author->last_name = 'Kono';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$translator = new Translator;
$translator->prefix = '';
$translator->first_name = 'ทินภาส';
$translator->last_name = 'พาหะนิชย์';
$translator->pseudonym = '';
$translator->save();
$book->translator()->attach($translator->id);
$book->cover_price         = 170.00;
$book->sell_price = 161.50;
$book->ISBN = '9786162870842';
$book->barcode = '9786162870842';
$book->type = 'ปกอ่อน';
$book->page = 216;
$book->width = 127;
$book->high = 184;
$book->deep = 13;
$book->weight = 210;
$book->publisher_name= 'วีเลิร์น, สนพ.';
$category = new Category;
$category->name = 'จิตวิทยาการจัดการและการบริหาร';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'บริหารธุรกิจ';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เพิ่มประสิทธิภาพให้เหนือกว่าคนอื่นเป็น 10 เท่า ด้วยเทคนิคการทำงานที่ง่ายจนใครๆ ก็มองข้าม';
$book->save();
$tag = new Tag;
$tag->name = 'การทำงาน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การบริหารจัดการ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'จิตวิทยาการบริหาร';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'หลักการทำงาน';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'Inspire คณิตศาสตร์ ป.6 พิชิตสอบเข้า ม.1 มั่นใจเต็ม 100';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/200/9786162005206L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'ณัฐสินี';
$author->last_name = 'ชลประทานชีพ';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 195.00;
$book->sell_price = 185.25;
$book->ISBN = '9786162005206';
$book->barcode = '9786162005206';
$book->type = 'ปกอ่อน';
$book->page = 258;
$book->width = 190;
$book->high = 255;
$book->deep = 15;
$book->weight = 475;
$book->publisher_name= 'ไอดีซี พรีเมียร์, บจก.';
$category = new Category;
$category->name = 'มัธยมต้น';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'คู่มือสอบเข้า';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เหมาะสำหรับนักเรียน ป.5 เเละ ป.6 ที่ต้องการยกระดับคะเเนนวิชาคณิตศาสตร์ให้สูงขึ้น เตรียมพร้อมสำหรับการสอบครั้งสำคัญทั้ง O-NET ป.6 เเละสอบเข้า ม.1 โรงเรียนชั้นนำ';
$book->save();
$tag = new Tag;
$tag->name = 'คู่มือสอบเข้า ม.ต้น';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'เตรียมสอบคณิตศาสตร์';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'คณิตศาสตร์ ป.6';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'เหตุใดเราจึงยังมีชีวิตอยู่';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/794/9786167942049L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = '';
$author->last_name = '';
$author->pseudonym = 'นิ้วกลม';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 195.00;
$book->sell_price = 185.25;
$book->ISBN = '9786167942049';
$book->barcode = '9786167942049';
$book->type = 'ปกอ่อน';
$book->page = 288;
$book->width = 126;
$book->high = 184;
$book->deep = 16;
$book->weight = 235;
$book->publisher_name= 'KOOB, สนพ.';
$category = new Category;
$category->name = 'ทั่วไป';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'วรรณกรรม';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'แล้วคุณอาจค้นพบความหมายชีวิตของคุณเอง';
$book->save();
$tag = new Tag;
$tag->name = 'วรรณกรรมไทย';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'เรื่องเล่า';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'รวมเรื่อง';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = '#เรียนหมอหนักมาก It\'s Not Easy to Be Doctor.';
$book->cover_pic = 'https://ws1.se-ed.com/Storage/Originals/978616/298/9786162982187L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'วิภาส';
$author->last_name = 'สุภัครพงษ์กุล';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 180.00;
$book->sell_price = 171.00;
$book->ISBN = '9786162982187';
$book->barcode = '9786162982187';
$book->type = 'ปกอ่อน';
$book->page = 160;
$book->width = 126;
$book->high = 182;
$book->deep = 11;
$book->weight = 205;
$book->publisher_name= 'SALMON BOOKS';
$category = new Category;
$category->name = 'ประสบการณ์ชีวิต';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'วรรณกรรม';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'พบกับมหากาพย์ชีวิตนักศึกษาแพทย์ บนเส้นทางแสนเพลีย';
$book->save();
$tag = new Tag;
$tag->name = 'เรื่องเล่า';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'แพทย์';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ประสบการณ์ชีวิต';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การแนะแนวการศึกษา';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'Perspective';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'เรียนไม่เก่งเป็นเจ้านาย เรียนแทบตายเป็นได้แค่ลูกจ้าง';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/082/9786160821808L.jpg';
$book->save();
$author = new Author;
$author->prefix = 'Robert';
$author->first_name = 'T.';
$author->last_name = 'Kiyosaki';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$translator = new Translator;
$translator->prefix = '';
$translator->first_name = 'จักรพงษ์';
$translator->last_name = 'เมษพันธุ์,';
$translator->pseudonym = '';
$translator->save();
$book->translator()->attach($translator->id);
$translator = new Translator;
$translator->prefix = '';
$translator->first_name = 'ธนกร';
$translator->last_name = 'นำรับพร';
$translator->pseudonym = '';
$translator->save();
$book->translator()->attach($translator->id);
$translator = new Translator;
$translator->prefix = '';
$translator->first_name = 'อมรเทพ';
$translator->last_name = 'ผันสิน';
$translator->pseudonym = '';
$translator->save();
$book->translator()->attach($translator->id);
$book->cover_price         = 320.00;
$book->sell_price = 288.00;
$book->ISBN = '9786160821808';
$book->barcode = '9786160821808';
$book->type = 'ปกอ่อน';
$book->page = 536;
$book->width = 145;
$book->high = 210;
$book->deep = 2;
$book->weight = 682;
$book->publisher_name= 'ซีเอ็ดยูเคชั่น, บมจ.';
$category = new Category;
$category->name = 'การเงิน การธนาคาร';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'บริหารธุรกิจ';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'แนวทางการสอนเรื่องเงินๆ ทองๆ ให้กับบุตรหลานของคุณในแบบของพ่อรวย เพื่อให้พวกเขาเริ่มต้นชีวิตทางการเงินได้อย่างถูกต้องและมีอิสรภาพทางการเงินในแบบที่ต้องการ';
$book->save();
$tag = new Tag;
$tag->name = 'การลงทุน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'พ่อรวยสอนลูก';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'Rich Dad Poor Dad';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การเงินส่วนบุคคล';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'โลหิตแห่งโอลิมปัส : The Blood of Olympus 5';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/061/9786160615520L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'Rick';
$author->last_name = 'Riordan';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$translator = new Translator;
$translator->prefix = '';
$translator->first_name = 'ดาวิษ';
$translator->last_name = 'ชาญชัยวานิช';
$translator->pseudonym = '';
$translator->save();
$book->translator()->attach($translator->id);
$book->cover_price         = 339.00;
$book->sell_price = 322.05;
$book->ISBN = '9786160615520';
$book->barcode = '9786160615520';
$book->type = 'ปกอ่อน';
$book->page = 528;
$book->width = 144;
$book->high = 210;
$book->deep = 27;
$book->weight = 530;
$book->publisher_name= 'เอ็นเธอร์บุ๊คส์, สนพ.';
$category = new Category;
$category->name = 'ผจญภัย';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'นวนิยาย';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = '"รูปปั้นอาธีน่าพาร์เธนอส" จะต้องถูกส่งคืนชาวกรีก สันติภาพระหว่างกรีกและโรมันจึงจะบังเกิด แล้วเทพเจ้าจะได้หายจากโรคบุคลิกภาพแปลกแยกสักที';
$book->save();
$tag = new Tag;
$tag->name = 'นวนิยายแฟนตาซี';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'นวนิยายผจญภัย';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'วรรณกรรมแปล';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'The Heroes of Olympus';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'วรรณกรรมเยาวชน';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'Fate Diary บันทึกพลิกโลก';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/042/9786160424245L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = '';
$author->last_name = '';
$author->pseudonym = 'Dr.Pop';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 275.00;
$book->sell_price = 261.25;
$book->ISBN = '9786160424245';
$book->barcode = '9786160424245';
$book->type = 'ปกอ่อน';
$book->page = 440;
$book->width = 140;
$book->high = 210;
$book->deep = 19;
$book->weight = 420;
$book->publisher_name= 'นานมีบุ๊คส์พับลิเคชั่นส์';
$category = new Category;
$category->name = 'ผจญภัย';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'นวนิยาย';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'ประวัติศาสตร์หน้าใหม่ของวงการหนังสือ นิยายไทยที่เปิดตัวด้วยยอดขายสูงสุดของนานมีบุ๊คส์ในรอบ 23 ปี! "Fate Diary (บันทึกพลิกโลก)" ปฐมบทแห่งปรากฏการณ์ซีรีส์ไซไฟแฟนตาซีครั้งใหม่จาก Dr.Pop';
$book->save();
$tag = new Tag;
$tag->name = 'นวนิยายไทย';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'นวนิยายแฟนตาซี';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'นวนิยายผจญภัย';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'พระพุทธเจ้า สอน How to สู่ความสำเร็จ';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/775/9786167752488L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'ราช';
$author->last_name = 'รามัญ';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 245.00;
$book->sell_price = 232.75;
$book->ISBN = '9786167752488';
$book->barcode = '9786167752488';
$book->type = 'ปกอ่อน';
$book->page = 256;
$book->width = 145;
$book->high = 208;
$book->deep = 14;
$book->weight = 315;
$book->publisher_name= 'สต็อคทูมอร์โรว์, สนพ.';
$category = new Category;
$category->name = 'ศาสนาประยุกต์';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'ศาสนา - ปรัชญา';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = '41 เคล็ดลับความรู้ที่มีมาเป็นพันปี เพื่อความสุขในชีวิต อย่างแท้จริง';
$book->save();
$tag = new Tag;
$tag->name = 'การพัฒนาตนเอง';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ความสำเร็จ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ศาสนาประยุกต์';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ศาสนาพุทธ';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'เปลี่ยนคุณเป็นคนใหม่ พูดอังกฤษได้เป๊ะเวอร์';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/527/9786165278164L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'Adam';
$author->last_name = 'Bradshaw';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 220.00;
$book->sell_price = 209.00;
$book->ISBN = '9786165278164';
$book->barcode = '9786165278164';
$book->type = 'ปกอ่อน';
$book->page = 336;
$book->width = 145;
$book->high = 210;
$book->deep = 21;
$book->weight = 340;
$book->publisher_name= 'ไอเก็ตอิงลิชพับลิชชิ่ง';
$category = new Category;
$category->name = 'การสนทนา การออกเสียง';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'ภาษาอังกฤษ';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เก่งอังกฤษ บันไดสู่งานดี เงินดี ชีวิตดี๊ดี พร้อมหรือยังที่จะเปลี่ยนภาษาอังกฤษ ของคุณให้เริด เพื่อเปิดประตูสู่โอกาสดีๆ ในชีวิต ทั้งเรื่องเรียน เรื่องงาน และเรื่องเงิน!';
$book->save();
$tag = new Tag;
$tag->name = 'การใช้ภาษาอังกฤษ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การสนทนาภาษาอังกฤษ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การพูดภาษาอังกฤษ';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'ร่างกายไม่เคยโกหก : What Every Body is Saying';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/287/9786162870750L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'Joe';
$author->last_name = 'Navarro';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$translator = new Translator;
$translator->prefix = '';
$translator->first_name = 'อมรรัตน์';
$translator->last_name = 'ศรีสุรินทร์';
$translator->pseudonym = '';
$translator->save();
$book->translator()->attach($translator->id);
$book->cover_price         = 195.00;
$book->sell_price = 185.25;
$book->ISBN = '9786162870750';
$book->barcode = '9786162870750';
$book->type = 'ปกอ่อน';
$book->page = 304;
$book->width = 143;
$book->high = 210;
$book->deep = 16;
$book->weight = 320;
$book->publisher_name= 'วีเลิร์น, สนพ.';
$category = new Category;
$category->name = 'จิตวิทยาบุคลิกภาพ';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'จิตวิทยา';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'คุณสามารถเป็นผู้เชี่ยวชาญด้านภาษากายได้ ไม่ว่าคุณจะต้องการความก้าวหน้าในชีวิตการงาน หรือแค่อยากเข้ากับเพื่อนๆ และครอบครัวให้ดีขึ้น หนังสือเล่มนี้เขียนมาเพื่อคุณ!';
$book->save();
$tag = new Tag;
$tag->name = 'จิตวิทยา';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'บุคลิกภาพ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การอ่านคน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ภาษาท่าทาง';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'มหัศจรรย์คลื่น ARC';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/515/9786165156202L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'อนันต์';
$author->last_name = 'ตันธุวนิตย์,';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$author = new Author;
$author->prefix = '';
$author->first_name = 'ภัทรวัลลิ์';
$author->last_name = 'หวังมิ่งมาศ';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 175.00;
$book->sell_price = 166.25;
$book->ISBN = '9786165156202';
$book->barcode = '9786165156202';
$book->type = 'ปกอ่อน';
$book->page = 184;
$book->width = 146;
$book->high = 208;
$book->deep = 11;
$book->weight = 230;
$book->publisher_name= 'เนชั่นบุ๊คส์, สนพ.';
$category = new Category;
$category->name = 'ธุรกิจขนาดเล็ก การลงทุน หุ้น';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'บริหารธุรกิจ';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'สุดยอดเครื่องมือทางเทคนิคที่นักลงทุนต้องอ่าน! จากประสบการณ์จริงกว่า 20 ปี ของกูรูนักวิเคราะห์ชื่อดัง';
$book->save();
$tag = new Tag;
$tag->name = 'การลงทุน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'หุ้น';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'จิตวิทยาการบริหาร';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'กลยุทธ์การบริหารธุรกิจ';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'สร้างล้านแรก ต้องแหกกฎ : The Risk Taker & IDOL Making';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978974/228/9789742282202L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'ภาววิทย์';
$author->last_name = 'กลิ่นประทุม,';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$author = new Author;
$author->prefix = '';
$author->first_name = 'พงษ์รพี';
$author->last_name = 'บูรณสมภพ';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 245.00;
$book->sell_price = 232.75;
$book->ISBN = '9789742282202';
$book->barcode = '9789742282202';
$book->type = 'ปกอ่อน';
$book->page = 336;
$book->width = 145;
$book->high = 210;
$book->deep = 20;
$book->weight = 410;
$book->publisher_name= 'โพสต์บุ๊กส์';
$category = new Category;
$category->name = 'จิตวิทยาการจัดการและการบริหาร';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'บริหารธุรกิจ';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เปลี่ยนแปลงตนเองเพื่อสร้างเงินล้าน ทำอย่างไร เคล็ดลับสำหรับมนุษย์เงินเดือนและทุกคนที่อยากรวย!';
$book->save();
$tag = new Tag;
$tag->name = 'การเงิน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การบริหารธุรกิจ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'จิตวิทยาการบริหาร';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การเงินส่วนบุคคล';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'ปราบลูกดื้อ รับมือลูกกินยาก';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/382/9786163824691L.jpg';
$book->save();
$author = new Author;
$author->prefix = 'พ.ญ.';
$author->first_name = 'เสาวภา';
$author->last_name = 'พรจินดารักษ์';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 229.00;
$book->sell_price = 217.55;
$book->ISBN = '9786163824691';
$book->barcode = '9786163824691';
$book->type = 'ปกอ่อน';
$book->page = 216;
$book->width = 142;
$book->high = 209;
$book->deep = 12;
$book->weight = 160;
$book->publisher_name= 'Happy Parenting, สนพ.';
$category = new Category;
$category->name = 'การเลี้ยงดูบุตร';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'ครอบครัว';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'คู่มือปฏิสัมพันธ์เชิงบวกในครอบครัว สอนลูกให้มีทั้งไอคิวและอีคิวได้ง่ายๆ รวมทุกเทคนิคเพื่อรับมือกับจอมเฮี้ยววัย 0-6 ปี ที่คุณอาจไม่เคยรู้';
$book->save();
$tag = new Tag;
$tag->name = 'ครอบครัว';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'คู่มือการเลี้ยงลูก';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การเลี้ยงดูบุตร';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'ไม่มีขา ใช่ว่าไม่มีลมหายใจ';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/180/9786161804770L.jpg';
$book->save();
$author = new Author;
$author->prefix = 'ร.ต.';
$author->first_name = 'ต่วนอัมรัน';
$author->last_name = 'กูโซะ';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 175.00;
$book->sell_price = 166.25;
$book->ISBN = '9786161804770';
$book->barcode = '9786161804770';
$book->type = 'ปกอ่อน';
$book->page = 180;
$book->width = 145;
$book->high = 210;
$book->deep = 12;
$book->weight = 240;
$book->publisher_name= 'แพรว, สนพ.';
$category = new Category;
$category->name = 'ประสบการณ์ชีวิต';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'วรรณกรรม';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เรื่องราวของทหารกล้าผู้เสียสละ เพื่อความสงบสุขของสามจังหวัดชายแดนภาคใต้';
$book->save();
$tag = new Tag;
$tag->name = 'ประสบการณ์ชีวิต';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ชีวประวัติบุคคล';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'ประเพณีอาเซียน';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/213/9786162135408L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'กฤชกร';
$author->last_name = 'เพชรนอก';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 119.00;
$book->sell_price = 113.05;
$book->ISBN = '9786162135408';
$book->barcode = '9786162135408';
$book->type = 'ปกอ่อน';
$book->page = 80;
$book->width = 189;
$book->high = 238;
$book->deep = 6;
$book->weight = 245;
$book->publisher_name= 'สกายบุ๊กส์, บจก.';
$category = new Category;
$category->name = 'หนังสือเตรียมความพร้อมสู่ประชาคมอาเซียน';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'ประชาคมเศรษฐกิจอาเซียน';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'สะท้อนวัฒนธรรมและความเชื่อของแต่ละประเทศ สามารถนำไปใช้เป็นความรู้รอบตัว และทำให้เกิดความเข้าใจประเพณีของประเทศต่างๆ ในอาเซียน เพื่อให้เราได้เรียนรู้และก้าวสู่ "ประชาคมอาเซียน" ไปพร้อมๆ กัน';
$book->save();
$tag = new Tag;
$tag->name = 'ประชาคมอาเซียน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ชุด ประชาคมอาเซียน ฉบับการ์ตูน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ขนบธรรมเนียมประเพณี';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'อาเซียนศึกษา : Asean Studies';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/538/9786165382137L.jpg';
$book->save();
$author = new Author;
$author->prefix = 'รศ.';
$author->first_name = 'ดนัย';
$author->last_name = 'ไชยโยธา';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 100.00;
$book->sell_price = 95.00;
$book->ISBN = '9786165382137';
$book->barcode = '9786165382137';
$book->type = 'ปกอ่อน';
$book->page = 144;
$book->width = 169;
$book->high = 239;
$book->deep = 6;
$book->weight = 195;
$book->publisher_name= 'โอเดียนสโตร์, สนพ.';
$category = new Category;
$category->name = 'หนังสือเตรียมความพร้อมสู่ประชาคมอาเซียน';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'ประชาคมเศรษฐกิจอาเซียน';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'ใช้ประกอบการเรียนการสอนและเสริมสาระในกลุ่มสาระการเรียนรู้สังคมศึกษา ศาสนา และวัฒนธรรม ภาษากะทัดรัด สรุปสาระอันควรเรียนและเพิ่มสาระในบางส่วน';
$book->save();
$tag = new Tag;
$tag->name = 'ประชาคมอาเซียน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'คู่มือเรียนอุดมศึกษา';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'สังคมศึกษามัธยมศึกษา';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'กลุ่มประเทศอาเซียน';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'ศัพท์เตรียมสอบ IELTS';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/797/9786167972015L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'ฝ่ายวิชาการสมาร์ท';
$author->last_name = 'อินเทลลิเจนท์';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 270.00;
$book->sell_price = 256.50;
$book->ISBN = '9786167972015';
$book->barcode = '9786167972015';
$book->type = 'ปกอ่อน';
$book->page = 252;
$book->width = 184;
$book->high = 259;
$book->deep = 15;
$book->weight = 625;
$book->publisher_name= 'สมาร์ท อินเทลลิเจนท์, บจก.';
$category = new Category;
$category->name = 'ศึกษาต่อต่างประเทศ';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'คู่มือสอบเข้า';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เตรียมตัวสอบ IELTS อย่างมั่นใจ ศัพท์ออกสอบบ่อย ตัวอย่างข้อสอบ เทคนิคเดาศัพท์ที่แม่นยำ ทำข้อสอบได้ชัวร์!';
$book->save();
$tag = new Tag;
$tag->name = 'คำศัพท์ภาษาอังกฤษ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การใช้ภาษาอังกฤษ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'IELTS';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'วิธีคิด วิธีรวย หมาน้อยสอนรวย ฉบับปรับปรุง';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978974/976/9789749760758L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'Bodo';
$author->last_name = 'Schafer';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$translator = new Translator;
$translator->prefix = '';
$translator->first_name = 'เจนจิรา';
$translator->last_name = 'เสรีโยธิน';
$translator->pseudonym = '';
$translator->save();
$book->translator()->attach($translator->id);
$book->cover_price         = 165.00;
$book->sell_price = 156.75;
$book->ISBN = '9789749760758';
$book->barcode = '9789749760758';
$book->type = 'ปกอ่อน';
$book->page = 176;
$book->width = 143;
$book->high = 206;
$book->deep = 9;
$book->weight = 190;
$book->publisher_name= 'บี มีเดีย, สนพ.';
$category = new Category;
$category->name = 'จิตวิทยาการจัดการและการบริหาร';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'บริหารธุรกิจ';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เรื่องราวสนุกสนานของ "หมาน้อย" กับ "เด็กหญิงคีรา" ที่สอนวิธีคิดง่ายๆ การหาเงิน เก็บเงิน และลงทุนให้มีฐานะมั่นคงร่ำรวย และมีอิสรภาพทางการเงิน';
$book->save();
$tag = new Tag;
$tag->name = 'การพัฒนาตนเอง';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การเงิน';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การบริหารธุรกิจ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'จิตวิทยาการจัดการ';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'ศัพท์อังกฤษสำหรับเด็กก่อนเข้า ป.1';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/527/9786165277686L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'ชนาภัทร';
$author->last_name = 'พรายมี';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 99.00;
$book->sell_price = 94.05;
$book->ISBN = '9786165277686';
$book->barcode = '9786165277686';
$book->type = 'ปกอ่อน';
$book->page = 108;
$book->width = 166;
$book->high = 188;
$book->deep = 66;
$book->weight = 195;
$book->publisher_name= 'เอ็มไอเอส, สนพ.';
$category = new Category;
$category->name = 'อนุบาล';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'คู่มือเรียน - สอบ';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เรียนรู้ศัพท์ภาษาอังกฤษจากรูปภาพ อ่านออก จำแม่น ก่อนเรียนในชั้น';
$book->save();
$tag = new Tag;
$tag->name = 'หนังสือภาพสำหรับเด็ก';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'คำศัพท์ภาษาอังกฤษ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ภาษาอังกฤษสำหรับเด็ก';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'คู่มือเรียนอนุบาล';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'รวมเล่ม เตรียมสอบ ป.2';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/885916/500/8859165000217L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'นวรัตน์';
$author->last_name = 'สุขเอม';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 129.00;
$book->sell_price = 122.55;
$book->width = 186;
$book->high = 260;
$book->deep = 10;
$book->weight = 390;
$book->publisher_name= 'สวัสดี ไอที, บจก.';
$category = new Category;
$category->name = 'ประถม';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'คู่มือเรียน - สอบ';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'รวมวิชาหลักทั้ง 5 กลุ่มสาระ เพื่อเตรียมความพร้อมก่อนสอบทั้งเทอม 1 และเทอม 2 สรุปเนื้อหาสั้นกระชับ เข้าใจง่าย เน้นความเข้าใจด้วยแบบฝึกหัดที่ครอบคลุม ตรงตามมาตรฐานการเรียนรู้และตัวชี้วัด';
$book->save();
$tag = new Tag;
$tag->name = 'คู่มือเรียนประถมศึกษา';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = '27 วิธีครองใจคน';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978616/275/9786162755712L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'ดุษฎี';
$author->last_name = 'ผลานุวัตร';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 220.00;
$book->sell_price = 209.00;
$book->ISBN = '9786162755712';
$book->barcode = '9786162755712';
$book->type = 'ปกอ่อน';
$book->page = 296;
$book->width = 146;
$book->high = 208;
$book->deep = 16;
$book->weight = 400;
$book->publisher_name= 'เอ็ดดูเคชั่น ไมน์ด ไลน์ มัลติมีเดีย';
$category = new Category;
$category->name = 'การพัฒนาตนเอง';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'จิตวิทยา';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = '27 ขั้นตอนง่ายๆ ที่คุณทำได้ สามารถเปลี่ยนแปลงทุกสถานการณ์ ให้ซ้ายหันขวาหันตามใจคุณ';
$book->save();
$tag = new Tag;
$tag->name = 'การพัฒนาตนเอง';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'จิตวิทยาประยุกต์';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การจูงใจ';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'เดอะท็อปซีเคร็ต';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978974/048/9789740481003L.gif';
$book->save();
$author = new Author;
$author->prefix = 'ท.พ.';
$author->first_name = 'สม';
$author->last_name = 'สุจีรา';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 215.00;
$book->sell_price = 204.25;
$book->ISBN = '9789740481003';
$book->barcode = '9789740481003';
$book->type = 'ปกอ่อน';
$book->page = 267;
$book->width = 145;
$book->high = 210;
$book->deep = 17;
$book->weight = 345;
$book->publisher_name= 'อมรินทร์ธรรมะ, สนพ.';
$category = new Category;
$category->name = 'การพัฒนาตนเอง';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'จิตวิทยา';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'สุดยอดความลับที่นำมาใช้ได้จริง อธิบายกระบวนการทำงาน วิธีปฏิบัติ และ"การสร้างภาพแห่งความรู้สึก" ที่จะทำให้คุณสมหวังทุกความปรารถนา';
$book->save();
$tag = new Tag;
$tag->name = '20 อันดับ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'The Top Secret';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'เดอะท็อปซีเคร็ต 2 ตอน ความลับสู่ความสำเร็จ';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978611/519/9786115190072L.gif';
$book->save();
$author = new Author;
$author->prefix = 'ท.พ.';
$author->first_name = 'สม';
$author->last_name = 'สุจีรา';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 235.00;
$book->sell_price = 223.25;
$book->ISBN = '9786115190072';
$book->barcode = '9786115190072';
$book->type = 'ปกอ่อน';
$book->page = 299;
$book->width = 146;
$book->high = 210;
$book->deep = 18;
$book->weight = 375;
$book->publisher_name= 'อมรินทร์ธรรมะ, สนพ.';
$category = new Category;
$category->name = 'ปีใหม่';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'เทศกาลและวันสำคัญ';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เผยทุกความลับแห่งความมสุขและความสำเร็จ จากทันตแพทย์ผู้เขย่าวงการธรรมะ จิตวิทยา และวิทยาศาสตร์';
$book->save();
$tag = new Tag;
$tag->name = 'ท.พ';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ความคิดและการคิด';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ศาสนา';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'พุทธศาสนา';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'เรียนเก่ง GET A++';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978974/414/9789744143648L.jpg';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'Dominic';
$author->last_name = 'O';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$translator = new Translator;
$translator->prefix = '';
$translator->first_name = 'จิตรลดา';
$translator->last_name = 'สิงห์คำ';
$translator->pseudonym = '';
$translator->save();
$book->translator()->attach($translator->id);
$book->cover_price         = 160.00;
$book->sell_price = 152.00;
$book->ISBN = '9789744143648';
$book->barcode = '9789744143648';
$book->type = 'ปกอ่อน';
$book->page = 160;
$book->width = 144;
$book->high = 209;
$book->deep = 10;
$book->weight = 260;
$book->publisher_name= 'เอ็กซเปอร์เน็ท, บจก.';
$category = new Category;
$category->name = 'การพัฒนาตนเอง';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'จิตวิทยา';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'เคล็ดลับใช้สมองเพื่อการเรียนรู้ เรียนต่อ สอบเข้า เพิ่มเกรด เหมาะสำหรับนักเรียน นักศึกษา ทุกระดับชั้น';
$book->save();
$tag = new Tag;
$tag->name = 'การพัฒนาตนเอง';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การจัดการการศึกษา';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การแนะแนวการศึกษา';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'ความจำ';
$tag->save();
$book->tag()->attach($tag->id);
$book = new Book;
$book->title = 'คู่มือฝึกเวทเทรนนิ่งอย่างมืออาชีพ ฉบับ Dumbbell Hardcore หล่อล่ำด้วยดัมบ์เบล';
$book->cover_pic          = 'https://ws1.se-ed.com/Storage/Originals/978974/350/9789743508318L.gif';
$book->save();
$author = new Author;
$author->prefix = '';
$author->first_name = 'คฑา';
$author->last_name = 'อาภรณ์';
$author->pseudonym = '';
$author->save();
$book->author()->attach($author->id);
$book->cover_price         = 295.00;
$book->sell_price = 280.25;
$book->ISBN = '9789743508318';
$book->barcode = '9789743508318';
$book->type = 'ปกอ่อน';
$book->page = 148;
$book->width = 169;
$book->high = 229;
$book->deep = 11;
$book->weight = 395;
$book->publisher_name= 'นิวเพลส 2005, คณะบุคคล';
$category = new Category;
$category->name = 'แอโรบิค การบริหารร่างกาย';
$category->save();
$book->category_id = $category->id;
$sub_category = new SubCategory;
$sub_category->name = 'สุขภาพ - ความงาม';
$sub_category->save();
$book->sub_category_id = $sub_category->id;
$book->description = 'หนักจริง โหดจริง ได้ผลจริง!';
$book->save();
$tag = new Tag;
$tag->name = 'การยกน้ำหนัก';
$tag->save();
$book->tag()->attach($tag->id);
$tag = new Tag;
$tag->name = 'การออกกำลังกาย';
$tag->save();
$book->tag()->attach($tag->id);


	}

}